project:
  type: book

book:
  # edit line below...
  title: "Project title"
  image: "img/lshtm_logo.jpg"
  date-format: "MMMM YYYY"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - references.qmd
    - appendices.qmd
  # edit line below...
  output-file: "[Candidate Number]_[MSc]_[Year of Submission]_Project.pdf"

bibliography: references.bib
csl: the-lancet.csl

################################################
#   Title page metadata - edit accordingly     #
################################################
candidate-number: "007"
msc-course: "Medical Statistics"
academic-year: "2023-24"
page-count: "0"
project-length: "Standard" # Extended (MSc IID only)
################################################

format:
  pdf:
    # include-in-header:
    #   - text: |
    #       \setlength{\beforechapskip}{3pt}
    keep-tex: false
    documentclass: scrreprt
    toc: true
    toc-depth: 2
    toc-title: "Table of contents"
    # lof: false
    # lot: false
    number-sections: true
    number-depth: 2
    papersize: a4
    geometry:
      - inner=2.54cm
      - outer=2.54cm
      - top=2.54cm
      - bottom=2.54cm
      - headsep=22pt
      - headheight=1pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    indent: false
    linestretch: 1.5
    fontsize: 11pt
    mainfont: "Arial"
    sansfont: "Arial"
    monofont: "Courier New"
    template-partials:
      - before-body.tex
